import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Pitch from "@/components/Pitch";
import WhyMe from "@/components/WhyMe";
import Projects from "@/components/Projects";
import CTA from "@/components/CTA";
import Contact from "@/components/Contact";
import { useState, useEffect } from "react";

import { sanityClient, urlFor } from "@/sanity";
import Title from "@/components/Title";

const inter = Inter({ subsets: ["latin"] });

export default function Home({
  projects,
  pageInfo,
  pitch,
  aboutme,
  contactInfo,
  cta,
}) {
  const [faviconIndex, setFaviconIndex] = useState(0);
  const faviconUrls = [
    //'░▒▓█',
    "▇▅▃▂▂▃▅▇█",
    "▇█▇▅▃▂▂▃▅",
    " ▂▃▅▇█▇▅▃▂",
    "▃▂▂▃▅▇█▇▅",
    //'▓▒░'
  ];

  //▇▅▃▂▂▃▅▇█
  //▅▇█▇▅▃▂▂▃
  //▂▃▅▇█▇▅▃▂
  //▂▂▃▅▇█▇▅▃

  useEffect(() => {
    const interval = setInterval(() => {
      // Change the favicon
      const title = document.querySelector("title");
      setFaviconIndex((prevIndex) => (prevIndex + 1) % faviconUrls.length);
      title.innerHTML = faviconUrls[faviconIndex];
    }, 500);

    return () => clearInterval(interval);
  }, []);

  return (
    <div className="">
      <Head>
        <title>Rozyn Studios {faviconUrls[faviconIndex]}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <meta name="theme-color" content="#ff0000" />
        <meta
          name="keywords"
          content="web developer, web dev, game dev, game developer, frontend, backend, marketing, game developer, game studio websites, e-sports team websites, website design, website development, website optimization, user experience, user interface, gaming industry, gaming websites, online gaming, mobile gaming, PC gaming, console gaming, game design, game marketing, game branding, e-sports marketing, e-sports branding, content creation, social media management, community management, game analytics"
        />
        <meta property="og:title" content="Ryzon Studios" />

        {/* <!-- Google tag (gtag.js) --> */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-NJ01PE63YY"
        ></script>
        <script>
          window.dataLayer = window.dataLayer || []; function gtag()
          {dataLayer.push(arguments)}
          gtag('js', new Date()); gtag('config', 'G-NJ01PE63YY');
        </script>

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {/* <h1 class="text-3xl font-bold text-red-700">sup</h1> */}

        {/* header */}

        <Header name={pageInfo?.compTitle} socials={pageInfo?.socials} />

        {/* hero */}

        <section id="hero">
          <Hero
            slogan={pageInfo?.slogan}
            desc={pageInfo?.desc}
            buttonTitle={pageInfo?.buttonTitle}
          />
        </section>

        {/* pitch */}

        <section id="pitch">
          <Pitch
            desc={pitch?.desc}
            pitchLine={pitch?.pitchLine}
            pitchImage={
              pitch?.pitchImage ? urlFor(pitch?.pitchImage)?.url() : ""
            }
          />
        </section>

        {/* why choose me */}

        <section id="whyme">
          <WhyMe title={aboutme?.title} desc={aboutme?.desc} />
        </section>

        {/* projects */}

        <section id="projects">
          <Title
            title={projects?.title}
            // absolute={true}
          />

          <Projects projects={projects} />
        </section>

        {/* call to action */}
        <section id="callToAction">
          <CTA
            title={cta?.title}
            desc={cta?.desc}
            buttonTitle={cta?.buttonTitle}
          />
        </section>

        {/* contact me */}

        <section id="contactMe">
          <Contact
            email={contactInfo?.email}
            phone={contactInfo?.phoneNumber}
            title={contactInfo?.title}
          />
        </section>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const pageInfo = await sanityClient.fetch('*[_type == "pageinfo"][0]');
  const pitch = await sanityClient.fetch('*[_type == "pitch"][0]');
  const aboutme = await sanityClient.fetch(`*[_type == "aboutme"][0]`);
  const contactInfo = await sanityClient.fetch('*[_type == "contactInfo"][0]');
  const cta = await sanityClient.fetch(`*[_type == "callToAction"][0]`);
  const projects = await sanityClient.fetch(`
  
  *[_type == "projects"][0] {
    ...,
    projs[] {
      _type == 'reference' => @->,
      _type != 'reference' => @
    }
  
  }
  
  
 
  `);

  console.log(pitch);
  return {
    props: {
      pageInfo,
      pitch,
      aboutme,
      contactInfo,
      cta,
      projects,
    },

    revalidate: 10,
  };
}
